## 퍼셉트론 알고리즘 예제 - p.347

In [2]:
## p.347  퍼셉트론 예제

import numpy as np

epsilon = 0.0000001        

def step_func(t):                       # 퍼셉트론의 활성화 함수(계단함수) 정의
    if t > epsilon: 
        return 1                        # 부동소수점 반올림하기
    else: return 0

X = np.array([                          # 훈련 데이터 세트
    [0, 0, 1],                          # 맨 끝의 1은 바이어스를 위한 입력 신호 1이다. 
    [0, 1, 1],                          # 맨 끝의 1은 바이어스를 위한 입력 신호 1이다. 
    [1, 0, 1],                          # 맨 끝의 1은 바이어스를 위한 입력 신호 1이다. 
    [1, 1, 1]                           # 맨 끝의 1은 바이어스를 위한 입력 신호 1이다. 
])

len(X)

4

In [3]:
# 정답을 저장하는 넘파이 행렬    
y = np.array([0, 0, 0, 1])

# 가중치 W의 초기값 [b, W1, W2]
W = np.array([0, 0, 0])                 
W

array([0, 0, 0])

In [4]:
def perceptron_fit(X, Y, epochs=10):    # 퍼셉트론 학습 알고리즘 구현
    global W
    eta = 0.2                           # 학습률

    for t in range(epochs):
        print("epoch=", t, "======================")
        for i in range(len(X)):                         # 샘플 수(4개)
            predict = step_func(np.dot(X[i], W))

            # 오차 계산 (오차 = 예측값 - 실제값)
            error = Y[i] - predict

            # 경사하강법: 가중치 업데이트 (error * X[i]: 미분값)
            W = W + eta * error * X[i]

            print("현재 처리 입력=",X[i],"정답=",Y[i],"출력=",predict,"변경된 가중치=", W)
        
        print("================================")

# 예측
def perceptron_predict(X, Y):
    global W
    for x in X:
         print(x[0], x[1], "->", step_func(np.dot(x, W)))

perceptron_fit(X, y, 6)
perceptron_predict(X, y)

epoch= 0 ======================
현재 처리 입력= [0 0 1] 정답= 0 출력= 0 변경된 가중치= [0. 0. 0.]
현재 처리 입력= [0 1 1] 정답= 0 출력= 0 변경된 가중치= [0. 0. 0.]
현재 처리 입력= [1 0 1] 정답= 0 출력= 0 변경된 가중치= [0. 0. 0.]
현재 처리 입력= [1 1 1] 정답= 1 출력= 0 변경된 가중치= [0.2 0.2 0.2]
epoch= 1 ======================
현재 처리 입력= [0 0 1] 정답= 0 출력= 1 변경된 가중치= [0.2 0.2 0. ]
현재 처리 입력= [0 1 1] 정답= 0 출력= 1 변경된 가중치= [ 0.2  0.  -0.2]
현재 처리 입력= [1 0 1] 정답= 0 출력= 0 변경된 가중치= [ 0.2  0.  -0.2]
현재 처리 입력= [1 1 1] 정답= 1 출력= 0 변경된 가중치= [0.4 0.2 0. ]
epoch= 2 ======================
현재 처리 입력= [0 0 1] 정답= 0 출력= 0 변경된 가중치= [0.4 0.2 0. ]
현재 처리 입력= [0 1 1] 정답= 0 출력= 1 변경된 가중치= [ 0.4  0.  -0.2]
현재 처리 입력= [1 0 1] 정답= 0 출력= 1 변경된 가중치= [ 0.2  0.  -0.4]
현재 처리 입력= [1 1 1] 정답= 1 출력= 0 변경된 가중치= [ 0.4  0.2 -0.2]
epoch= 3 ======================
현재 처리 입력= [0 0 1] 정답= 0 출력= 0 변경된 가중치= [ 0.4  0.2 -0.2]
현재 처리 입력= [0 1 1] 정답= 0 출력= 0 변경된 가중치= [ 0.4  0.2 -0.2]
현재 처리 입력= [1 0 1] 정답= 0 출력= 1 변경된 가중치= [ 0.2  0.2 -0.4]
현재 처리 입력= [1 1 1] 정답= 1 출력= 0 변경된 가중치= [ 0.4  0.4 -0.2]
epoch=

### 퍼셉트론을 sklearn의 Perceptron class로 학습하기

In [5]:
## p.349
from sklearn.linear_model import Perceptron
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

In [6]:
# 퍼셉트론 모델 정의: 2진 분류
clf = Perceptron()

# 모델 학습 -> 내부적으로 W, b등 Weight를 학습으로 찾았음
clf.fit(X, y)

Perceptron()

In [7]:
# W (Weight)
clf.coef_

array([[2., 2.]])

In [8]:
# bias
clf.intercept_

array([-2.])

In [9]:
# 모델 평가
accuracy = clf.score(X, y)
accuracy

1.0

In [10]:
# 예측
clf.predict(X)

array([0, 0, 0, 1])

In [11]:
X, y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 0, 0, 1]))

In [12]:
clf.predict([[1, 0]])

array([0])

#### OR Gate

In [13]:
### sklearn으로 퍼셉트론 실습 (p.350)
from sklearn.linear_model import Perceptron
import numpy as np

# 학습예제와 정답 레이블
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# OR
y = np.array([0, 1, 1, 1])

# 퍼셉트론 모델 정의: 2진분류
clf = Perceptron(tol =1e-3, random_state = 0)

# 모델 학습
clf.fit(X, y)
clf.predict(X)

array([0, 1, 1, 1])

In [14]:
# 정확도
clf.score(X, y)

1.0

In [15]:
# 학습된 parameter(Weight)
clf.coef_, clf.intercept_

(array([[2., 2.]]), array([-1.]))

### 03 퍼셉트론의 한계성 (XOR)

In [16]:
### sklearn으로 퍼셉트론 실습 (p.349)
from sklearn.linear_model import Perceptron
import numpy as np

# 학습예제와 정답 레이블
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# XOR
y = np.array([0, 1, 1, 0])

In [17]:
# 퍼셉트론 모델 정의: 2진분류 
clf = Perceptron (tol = 1e-3, random_state = 0)

# 모델 학습
clf.fit(X, y)

# 모델 예측
clf.predict(X)

array([0, 0, 0, 0])

In [18]:
# 정확도 -> 퍼셉트론으로 XOR의 문제를 해결할 수 없음
clf.score(X, y)

0.5